-- Hand-written migration. Drizzle cannot express cross-schema references to
-- `auth.users` (a table Supabase owns) or Postgres triggers, so this file is
-- maintained by hand and MUST NOT be regenerated by `drizzle-kit generate`.
--
-- Applies:
--   1. FK from public.profiles -> auth.users, cascading deletes
--   2. a case-insensitive unique index on email
--   3. set_updated_at(), reused by every table added from Phase 1 onward
--   4. handle_new_user(), which creates the profile row on sign-up

--> statement-breakpoint
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_auth_users_id_fk"
  FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_email_lower_idx" ON "profiles" (lower("email"));

--> statement-breakpoint
-- Keeps updated_at honest regardless of which code path writes the row.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

--> statement-breakpoint
CREATE TRIGGER "profiles_set_updated_at"
  BEFORE UPDATE ON "profiles"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

--> statement-breakpoint
-- Runs as the definer because the trigger fires in the auth service's context,
-- which has no rights on `public`. search_path is pinned to defeat the
-- search-path hijack that SECURITY DEFINER functions are prone to.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name, avatar_url)
  VALUES (
    NEW.id,
    lower(NEW.email),
    nullif(trim(coalesce(
      NEW.raw_user_meta_data ->> 'display_name',
      NEW.raw_user_meta_data ->> 'full_name',
      NEW.raw_user_meta_data ->> 'name',
      ''
    )), ''),
    nullif(trim(coalesce(NEW.raw_user_meta_data ->> 'avatar_url', '')), '')
  )
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
END;
$$;

--> statement-breakpoint
DROP TRIGGER IF EXISTS "on_auth_user_created" ON auth.users;

--> statement-breakpoint
CREATE TRIGGER "on_auth_user_created"
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

--> statement-breakpoint
-- Keep the profile's email in step when the user changes it via Supabase Auth.
CREATE OR REPLACE FUNCTION public.handle_user_email_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE public.profiles
  SET email = lower(NEW.email)
  WHERE id = NEW.id;

  RETURN NEW;
END;
$$;

--> statement-breakpoint
DROP TRIGGER IF EXISTS "on_auth_user_email_changed" ON auth.users;

--> statement-breakpoint
CREATE TRIGGER "on_auth_user_email_changed"
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW
  WHEN (OLD.email IS DISTINCT FROM NEW.email)
  EXECUTE FUNCTION public.handle_user_email_change();

--> statement-breakpoint
-- Isolation is enforced in the application (see CLAUDE.md), so `profiles` is
-- not reachable by the anon/authenticated PostgREST roles at all. Revoking is
-- what makes "we don't use RLS" safe rather than merely intentional.
REVOKE ALL ON TABLE public.profiles FROM anon, authenticated;
