-- Hand-written companion to 0002. Drizzle cannot express cross-schema FKs to
-- auth.users, expression indexes, triggers, grants, or seed data, so they live
-- here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users =============================
-- CASCADE where the row is meaningless without the user (membership, admin
-- grant, an in-flight impersonation). SET NULL where the row is history that
-- must outlive the user (audit, "invited_by", "created_by").

--> statement-breakpoint
ALTER TABLE "tenants"
  ADD CONSTRAINT "tenants_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "tenant_members"
  ADD CONSTRAINT "tenant_members_user_id_users_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

--> statement-breakpoint
ALTER TABLE "tenant_members"
  ADD CONSTRAINT "tenant_members_invited_by_users_fk"
  FOREIGN KEY ("invited_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "tenant_invitations"
  ADD CONSTRAINT "tenant_invitations_invited_by_users_fk"
  FOREIGN KEY ("invited_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "tenant_invitations"
  ADD CONSTRAINT "tenant_invitations_accepted_user_id_users_fk"
  FOREIGN KEY ("accepted_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "platform_admins"
  ADD CONSTRAINT "platform_admins_user_id_users_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

--> statement-breakpoint
ALTER TABLE "platform_admins"
  ADD CONSTRAINT "platform_admins_granted_by_users_fk"
  FOREIGN KEY ("granted_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
-- audit_logs.actor is SET NULL, never CASCADE: deleting a user must not erase
-- the record of what they did. audit_logs.tenant_id has no FK at all, on
-- purpose, so the trail survives tenant deletion too.
ALTER TABLE "audit_logs"
  ADD CONSTRAINT "audit_logs_actor_user_id_users_fk"
  FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "impersonation_sessions"
  ADD CONSTRAINT "impersonation_sessions_actor_user_id_users_fk"
  FOREIGN KEY ("actor_user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- === Case-insensitive tenant slug uniqueness ============================
--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_slug_lower_idx" ON "tenants" (lower("slug")) WHERE "deleted_at" IS NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
--> statement-breakpoint
CREATE TRIGGER "tenants_set_updated_at" BEFORE UPDATE ON "tenants"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "roles_set_updated_at" BEFORE UPDATE ON "roles"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "tenant_members_set_updated_at" BEFORE UPDATE ON "tenant_members"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "tenant_member_roles_set_updated_at" BEFORE UPDATE ON "tenant_member_roles"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "tenant_invitations_set_updated_at" BEFORE UPDATE ON "tenant_invitations"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "platform_admins_set_updated_at" BEFORE UPDATE ON "platform_admins"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Audit log is append-only ===========================================
-- Enforced against every writer, including the application's own role, because
-- an audit trail that the app can quietly rewrite is not an audit trail.
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.reject_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_logs is append-only; % is not permitted', TG_OP;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "audit_logs_no_update" BEFORE UPDATE ON "audit_logs"
  FOR EACH ROW EXECUTE FUNCTION public.reject_mutation();
--> statement-breakpoint
CREATE TRIGGER "audit_logs_no_delete" BEFORE DELETE ON "audit_logs"
  FOR EACH ROW EXECUTE FUNCTION public.reject_mutation();

-- === Isolation: no PostgREST access to any Phase 1 table ================
-- Same contract as profiles in 0001 — with RLS off, the anon/authenticated
-- roles must not reach these tables at all. Every new table repeats this.
--> statement-breakpoint
REVOKE ALL ON TABLE
  public.tenants,
  public.roles,
  public.tenant_members,
  public.tenant_member_roles,
  public.tenant_invitations,
  public.platform_admins,
  public.audit_logs,
  public.impersonation_sessions
FROM anon, authenticated;

-- === Seed the system roles (spec §4.3) ==================================
-- Kept in sync with src/server/authz/roles.ts. Seeded here so the FK target
-- exists before any membership is created; the seed script re-upserts these
-- from code to catch description/order edits.
--> statement-breakpoint
INSERT INTO "roles" ("key", "name", "description", "is_system", "sort_order") VALUES
  ('owner',            'Owner',            'Full control of the organizer workspace, including billing and members.', true, 0),
  ('event_manager',    'Event Manager',    'Creates and runs events, booths, and maps; reviews merchants.',           true, 1),
  ('merchant_manager', 'Merchant Manager', 'Onboards and manages merchants and their listings.',                      true, 2),
  ('marketing',        'Marketing',        'Runs campaigns, vouchers, and featured placements.',                      true, 3),
  ('finance',          'Finance',          'Manages billing and exports financial and engagement reports.',           true, 4),
  ('checker',          'Checker',          'Validates and redeems vouchers on-site.',                                 true, 5),
  ('support',          'Support',          'Read access across the workspace to assist users.',                       true, 6),
  ('analyst',          'Read-only Analyst','Views and exports analytics only.',                                       true, 7)
ON CONFLICT ("key") DO UPDATE
  SET "name" = EXCLUDED."name",
      "description" = EXCLUDED."description",
      "sort_order" = EXCLUDED."sort_order";
