-- Hand-written companion to 0004. Drizzle cannot express the cross-schema FK to
-- auth.users, the lower(slug) partial unique index, triggers, or grants, so they
-- live here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign key to auth.users =============================
-- SET NULL, never CASCADE: an event must outlive the staff account that made it
-- (same rule as tenants.created_by in 0003).
--> statement-breakpoint
ALTER TABLE "events"
  ADD CONSTRAINT "events_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === Case-insensitive slug uniqueness, scoped per tenant ================
-- Event slugs are unique WITHIN a tenant (the public URL is /{tenant}/{event}),
-- so two organizers may reuse a slug. Partial, so a soft-deleted event's slug
-- can be reused. Drizzle cannot express lower() in an index.
--> statement-breakpoint
CREATE UNIQUE INDEX "events_tenant_slug_lower_idx"
  ON "events" ("tenant_id", lower("slug")) WHERE "deleted_at" IS NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
--> statement-breakpoint
CREATE TRIGGER "events_set_updated_at" BEFORE UPDATE ON "events"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "event_settings_set_updated_at" BEFORE UPDATE ON "event_settings"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "event_branding_set_updated_at" BEFORE UPDATE ON "event_branding"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "event_operating_hours_set_updated_at" BEFORE UPDATE ON "event_operating_hours"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 2 table ================
-- With RLS off, the anon/authenticated roles must not reach these tables at all.
-- Every new table repeats this revoke — it is what makes "no RLS" safe.
--> statement-breakpoint
REVOKE ALL ON TABLE
  public.events,
  public.event_settings,
  public.event_branding,
  public.event_operating_hours
FROM anon, authenticated;
