-- Hand-written companion to 0006. Drizzle cannot express cross-schema FKs to
-- auth.users, the lower(slug) partial unique indexes, triggers, or grants, so
-- they live here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users =============================
-- CASCADE where the row is meaningless without the user (a merchant membership);
-- SET NULL where the row is history that must outlive the user (who invited /
-- reviewed / created).

--> statement-breakpoint
ALTER TABLE "merchant_members"
  ADD CONSTRAINT "merchant_members_user_id_users_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

--> statement-breakpoint
ALTER TABLE "merchant_members"
  ADD CONSTRAINT "merchant_members_invited_by_users_fk"
  FOREIGN KEY ("invited_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "merchant_invitations"
  ADD CONSTRAINT "merchant_invitations_invited_by_users_fk"
  FOREIGN KEY ("invited_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "merchant_invitations"
  ADD CONSTRAINT "merchant_invitations_accepted_user_id_users_fk"
  FOREIGN KEY ("accepted_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "merchants"
  ADD CONSTRAINT "merchants_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "merchant_event_participations"
  ADD CONSTRAINT "merchant_event_participations_reviewed_by_users_fk"
  FOREIGN KEY ("reviewed_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === Case-insensitive slug uniqueness, scoped per tenant ================
--> statement-breakpoint
CREATE UNIQUE INDEX "merchants_tenant_slug_lower_idx"
  ON "merchants" ("tenant_id", lower("slug")) WHERE "deleted_at" IS NULL;
--> statement-breakpoint
CREATE UNIQUE INDEX "merchant_categories_tenant_slug_lower_idx"
  ON "merchant_categories" ("tenant_id", lower("slug"));

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
--> statement-breakpoint
CREATE TRIGGER "merchant_categories_set_updated_at" BEFORE UPDATE ON "merchant_categories"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "merchants_set_updated_at" BEFORE UPDATE ON "merchants"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "merchant_members_set_updated_at" BEFORE UPDATE ON "merchant_members"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "merchant_invitations_set_updated_at" BEFORE UPDATE ON "merchant_invitations"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "merchant_event_participations_set_updated_at" BEFORE UPDATE ON "merchant_event_participations"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "listing_items_set_updated_at" BEFORE UPDATE ON "listing_items"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 3 table ================
-- With RLS off, the anon/authenticated roles must not reach these tables at all.
--> statement-breakpoint
REVOKE ALL ON TABLE
  public.merchant_categories,
  public.merchants,
  public.merchant_members,
  public.merchant_invitations,
  public.merchant_event_participations,
  public.listing_items
FROM anon, authenticated;
