-- Hand-written companion to 0008. Drizzle cannot express cross-schema FKs to
-- auth.users, the lower(booth_number) partial unique index, the partial-unique
-- "one active assignment" indexes, triggers, or grants, so they live here and
-- MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users =============================
-- SET NULL: the row is history that must outlive the user who uploaded /
-- assigned it (files.created_by, booth_assignments.assigned_by).

--> statement-breakpoint
ALTER TABLE "files"
  ADD CONSTRAINT "files_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

--> statement-breakpoint
ALTER TABLE "booth_assignments"
  ADD CONSTRAINT "booth_assignments_assigned_by_users_fk"
  FOREIGN KEY ("assigned_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === Case-insensitive booth-number uniqueness, scoped per event =========
--> statement-breakpoint
CREATE UNIQUE INDEX "booths_event_number_lower_idx"
  ON "booths" ("event_id", lower("booth_number"));

-- === One active assignment per booth and per participation ==============
-- A cancelled assignment is history; only non-cancelled rows must be unique, so
-- reassigning means cancel-then-insert rather than update-in-place.
--> statement-breakpoint
CREATE UNIQUE INDEX "booth_assignments_booth_active_uq"
  ON "booth_assignments" ("booth_id") WHERE "status" <> 'cancelled';
--> statement-breakpoint
CREATE UNIQUE INDEX "booth_assignments_participation_active_uq"
  ON "booth_assignments" ("participation_id") WHERE "status" <> 'cancelled';

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
--> statement-breakpoint
CREATE TRIGGER "files_set_updated_at" BEFORE UPDATE ON "files"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "zones_set_updated_at" BEFORE UPDATE ON "zones"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "maps_set_updated_at" BEFORE UPDATE ON "maps"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "map_floors_set_updated_at" BEFORE UPDATE ON "map_floors"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "booths_set_updated_at" BEFORE UPDATE ON "booths"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "booth_assignments_set_updated_at" BEFORE UPDATE ON "booth_assignments"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 4 table ================
-- With RLS off, the anon/authenticated roles must not reach these tables at all.
--> statement-breakpoint
REVOKE ALL ON TABLE
  public.files,
  public.zones,
  public.maps,
  public.map_floors,
  public.booths,
  public.booth_assignments
FROM anon, authenticated;
