-- Hand-written companion to 0010. Drizzle cannot express the cross-schema FK to
-- auth.users, the triggers, or the grants, so they live here and MUST NOT be
-- regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign key to auth.users =============================
-- SET NULL: a visitor row outlives any future account link. `user_id` is reserved
-- for the anonymous→account merge; the visitor is real without it.

--> statement-breakpoint
ALTER TABLE "visitors"
  ADD CONSTRAINT "visitors_user_id_users_fk"
  FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
-- visitor_favourites is append/delete only (no updated_at), so it has no trigger.
--> statement-breakpoint
CREATE TRIGGER "visitors_set_updated_at" BEFORE UPDATE ON "visitors"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "visitor_recent_views_set_updated_at" BEFORE UPDATE ON "visitor_recent_views"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 5 table ================
-- With RLS off, the anon/authenticated roles must not reach these tables at all.
-- Visitor rows are written only by the server (the visitor service), never via
-- PostgREST — the anon key stays auth-only.
--> statement-breakpoint
REVOKE ALL ON TABLE
  public.visitors,
  public.visitor_favourites,
  public.visitor_recent_views
FROM anon, authenticated;
