-- Hand-written companion to 0012. Drizzle cannot express the cross-schema FK to
-- auth.users, the triggers, the partial unique index, or the grants, so they live
-- here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign key to auth.users ============================
-- SET NULL: a placement outlives the user who created it (staff churn).

--> statement-breakpoint
ALTER TABLE "featured_placements"
  ADD CONSTRAINT "featured_placements_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === One open placement per participation ==============================
-- A participation can have at most one placement with no end date (currently
-- featured). Expired placements (ends_at set) are history and don't collide.

--> statement-breakpoint
CREATE UNIQUE INDEX "featured_placements_open_participation_uq"
  ON "featured_placements" ("participation_id")
  WHERE "ends_at" IS NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
-- usage_records is append-only (no updated_at), so it has no trigger.

--> statement-breakpoint
CREATE TRIGGER "plans_set_updated_at" BEFORE UPDATE ON "plans"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "subscriptions_set_updated_at" BEFORE UPDATE ON "subscriptions"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "invoices_set_updated_at" BEFORE UPDATE ON "invoices"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "featured_placements_set_updated_at" BEFORE UPDATE ON "featured_placements"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 6 table ================
-- With RLS off, anon/authenticated must not reach these tables at all. `plans`
-- is a public catalog but is still read only through the repository layer (the
-- anon key stays auth-only), so it is revoked too.

--> statement-breakpoint
REVOKE ALL ON TABLE
  public.plans,
  public.subscriptions,
  public.invoices,
  public.usage_records,
  public.featured_placements
FROM anon, authenticated;
