-- Hand-written companion to 0014. Drizzle cannot express the cross-schema FK to
-- auth.users, the triggers, the partial unique index, or the grants, so they live
-- here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign key to auth.users ============================
-- SET NULL: a QR code outlives the staff member who generated it.

--> statement-breakpoint
ALTER TABLE "qr_codes"
  ADD CONSTRAINT "qr_codes_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === One active code per target ========================================
-- A given target (e.g. this merchant's listing) has at most one active,
-- non-expired code, so `getOrCreate…` is idempotent. Disabled codes
-- (is_active = false) are history and don't collide; the `url` target type has a
-- null target_id and is exempt.

--> statement-breakpoint
CREATE UNIQUE INDEX "qr_codes_open_target_uq"
  ON "qr_codes" ("target_type", "target_id")
  WHERE "target_id" IS NOT NULL AND "is_active";

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
-- analytics_events and qr_scan_events are append-only (no updated_at), so they
-- get no trigger. The rollups and qr_codes are mutable.

--> statement-breakpoint
CREATE TRIGGER "daily_event_metrics_set_updated_at" BEFORE UPDATE ON "daily_event_metrics"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "daily_merchant_metrics_set_updated_at" BEFORE UPDATE ON "daily_merchant_metrics"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "qr_codes_set_updated_at" BEFORE UPDATE ON "qr_codes"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 7 table ================
-- With RLS off, anon/authenticated must not reach these tables at all. The `/q`
-- redirect and the tracking beacon reach them only through the repository layer
-- (service role / server), never the anon key.

--> statement-breakpoint
REVOKE ALL ON TABLE
  public.analytics_events,
  public.daily_event_metrics,
  public.daily_merchant_metrics,
  public.qr_codes,
  public.qr_scan_events
FROM anon, authenticated;
