-- Hand-written companion to 0016. Drizzle cannot express the cross-schema FKs to
-- auth.users, the triggers, or the grants, so they live here and MUST NOT be
-- regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users ===========================
-- SET NULL throughout: a voucher, a redemption record, and a campaign all
-- outlive the staff member who created or performed them (staff churn), and the
-- historical row must survive.

--> statement-breakpoint
ALTER TABLE "vouchers"
  ADD CONSTRAINT "vouchers_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "voucher_redemptions"
  ADD CONSTRAINT "voucher_redemptions_redeemed_by_users_fk"
  FOREIGN KEY ("redeemed_by_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "campaigns"
  ADD CONSTRAINT "campaigns_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === Active-voucher lookup =============================================
-- The public list asks "claimable vouchers for this event" on every visit; index
-- the live rows only, so the index stays small as archived vouchers accumulate.

--> statement-breakpoint
CREATE INDEX "vouchers_event_active_idx"
  ON "vouchers" ("event_id", "starts_at")
  WHERE "status" = 'active' AND "deleted_at" IS NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======
-- voucher_redemptions is append-only (no updated_at), so it has no trigger.

--> statement-breakpoint
CREATE TRIGGER "vouchers_set_updated_at" BEFORE UPDATE ON "vouchers"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "voucher_codes_set_updated_at" BEFORE UPDATE ON "voucher_codes"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "voucher_claims_set_updated_at" BEFORE UPDATE ON "voucher_claims"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "campaigns_set_updated_at" BEFORE UPDATE ON "campaigns"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "campaign_audiences_set_updated_at" BEFORE UPDATE ON "campaign_audiences"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "campaign_messages_set_updated_at" BEFORE UPDATE ON "campaign_messages"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "notification_deliveries_set_updated_at" BEFORE UPDATE ON "notification_deliveries"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Isolation: no PostgREST access to any Phase 8 table ================
-- With RLS off, anon/authenticated must not reach these tables at all. The public
-- claim path reaches them only through the repository layer (server-side), never
-- the anon key — a visitor must not be able to read the code table directly.

--> statement-breakpoint
REVOKE ALL ON TABLE
  public.vouchers,
  public.voucher_codes,
  public.voucher_claims,
  public.voucher_redemptions,
  public.campaigns,
  public.campaign_audiences,
  public.campaign_messages,
  public.notification_deliveries
FROM anon, authenticated;
