-- Hand-written companion to 0018. Drizzle cannot express the cross-schema FKs to
-- auth.users, the triggers, the partial index, or the grants, so they live here
-- and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users ===========================
-- SET NULL: a sponsor and its bookings outlive the staff member who created
-- them (staff churn), and the historical row must survive.

--> statement-breakpoint
ALTER TABLE "sponsors"
  ADD CONSTRAINT "sponsors_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "ad_bookings"
  ADD CONSTRAINT "ad_bookings_created_by_users_fk"
  FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === updated_at triggers (reuses public.set_updated_at from 0001) =======

--> statement-breakpoint
CREATE TRIGGER "sponsors_set_updated_at" BEFORE UPDATE ON "sponsors"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
--> statement-breakpoint
CREATE TRIGGER "ad_bookings_set_updated_at" BEFORE UPDATE ON "ad_bookings"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Ad-serving lookup =================================================
-- Every visitor page render asks "live bookings for this event + slot". Index
-- the servable rows only, so the index stays small as paused/archived and
-- finished flights accumulate over successive events.

--> statement-breakpoint
CREATE INDEX "ad_bookings_live_idx"
  ON "ad_bookings" ("event_id", "slot", "starts_at", "ends_at")
  WHERE "status" = 'active';

-- === Sanity guards =====================================================
-- Enforced in the service too, but a bad flight window or a non-positive weight
-- is a data-integrity problem, not just a validation message.

--> statement-breakpoint
ALTER TABLE "ad_bookings"
  ADD CONSTRAINT "ad_bookings_window_ck"
  CHECK ("starts_at" IS NULL OR "ends_at" IS NULL OR "ends_at" >= "starts_at");
--> statement-breakpoint
ALTER TABLE "ad_bookings"
  ADD CONSTRAINT "ad_bookings_weight_ck" CHECK ("weight" > 0);

-- === Isolation: no PostgREST access to the Phase 9 tables ===============
-- With RLS off, anon/authenticated must not reach these tables at all. The
-- public ad surface reads exclusively through the repository layer, which
-- filters by the event's public status — never by a client-supplied tenant_id.

--> statement-breakpoint
REVOKE ALL ON TABLE
  public.sponsors,
  public.ad_bookings
FROM anon, authenticated;
