-- Hand-written companion to 0020. Drizzle cannot express the cross-schema FKs to
-- auth.users, the triggers, the partial/expression indexes, the CHECKs, or the
-- grants, so they live here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users ===========================
-- SET NULL on the author: deleting an account must not delete the event's
-- content. `visitor_id` stays NOT NULL and remains the authoritative owner for
-- every permission check, so an orphaned author id never widens access.
-- SET NULL on the moderator for the same staff-churn reason as sponsors (0019).

--> statement-breakpoint
ALTER TABLE "moment_posts"
  ADD CONSTRAINT "moment_posts_author_user_id_users_fk"
  FOREIGN KEY ("author_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "moment_posts"
  ADD CONSTRAINT "moment_posts_hidden_by_users_fk"
  FOREIGN KEY ("hidden_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === updated_at trigger (reuses public.set_updated_at from 0001) ========

--> statement-breakpoint
CREATE TRIGGER "moment_posts_set_updated_at" BEFORE UPDATE ON "moment_posts"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === One visitor row per account ========================================
-- `visitors.user_id` was reserved from Phase 5 for the anonymous→account link
-- that Moments finally makes. Partial UNIQUE so the (many) anonymous rows are
-- unaffected while a signed-in visitor can only ever resolve to one row —
-- otherwise signing in on a second device would silently fork the identity, and
-- your posts would follow the cookie rather than the account.

--> statement-breakpoint
CREATE UNIQUE INDEX "visitors_user_id_uq"
  ON "visitors" ("user_id")
  WHERE "user_id" IS NOT NULL;

-- === Feed lookup ========================================================
-- The public feed is always "this event's published posts, newest first". Index
-- exactly that, DESC, and only the published rows so hidden/deleted posts don't
-- bloat it as moderation accumulates. Drizzle's generated
-- moment_posts_event_created_idx stays for the moderation queue, which reads
-- every status.

--> statement-breakpoint
CREATE INDEX "moment_posts_feed_idx"
  ON "moment_posts" ("event_id", "created_at" DESC)
  WHERE "status" = 'published';

-- === Content rules ======================================================
-- The service validates all three and returns friendly messages. These are the
-- guarantee: validation can be bypassed by a future code path, a constraint
-- cannot.

--> statement-breakpoint
ALTER TABLE "moment_posts"
  ADD CONSTRAINT "moment_posts_rating_range_ck"
  CHECK ("rating" IS NULL OR ("rating" >= 1 AND "rating" <= 5));

-- A star rating is a judgement *about a stall*; without one there is nothing for
-- it to be about and nothing to aggregate it into.
--> statement-breakpoint
ALTER TABLE "moment_posts"
  ADD CONSTRAINT "moment_posts_rating_needs_stall_ck"
  CHECK ("rating" IS NULL OR "participation_id" IS NOT NULL);

-- "Text-only posts are allowed" is not "empty posts are allowed".
-- NOTE: this predicate is replaced in 0022 — `btrim` trims spaces only, so a
-- newline-only body slipped through. Left as-was so the migration history stays
-- an accurate record of what ran.
--> statement-breakpoint
ALTER TABLE "moment_posts"
  ADD CONSTRAINT "moment_posts_has_content_ck"
  CHECK ("image_file_id" IS NOT NULL OR btrim(coalesce("body", '')) <> '');

-- === Isolation: no PostgREST access to the Phase 10 table ===============
-- With RLS off, anon/authenticated must not reach this table at all. The public
-- feed reads exclusively through the repository layer, which filters by the
-- event's public status and the post's published status — never by a
-- client-supplied tenant_id.

--> statement-breakpoint
REVOKE ALL ON TABLE public.moment_posts FROM anon, authenticated;
