-- Hand-written companion to 0023. Drizzle cannot express the cross-schema FKs to
-- auth.users, the trigger, the partial index, the CHECK, or the grants, so they
-- live here and MUST NOT be regenerated by `drizzle-kit generate`.

-- === Cross-schema foreign keys to auth.users ===========================
-- SET NULL for the same reason as moment_posts (0021): deleting an account must
-- not delete the event's content, and `visitor_id` stays NOT NULL as the
-- authoritative owner for every permission check.

--> statement-breakpoint
ALTER TABLE "moment_comments"
  ADD CONSTRAINT "moment_comments_author_user_id_users_fk"
  FOREIGN KEY ("author_user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;
--> statement-breakpoint
ALTER TABLE "moment_comments"
  ADD CONSTRAINT "moment_comments_hidden_by_users_fk"
  FOREIGN KEY ("hidden_by") REFERENCES "auth"."users"("id") ON DELETE SET NULL;

-- === updated_at trigger (reuses public.set_updated_at from 0001) ========
-- Likes deliberately have none: the table is append/delete only and carries no
-- `updated_at` column, like visitor_favourites.

--> statement-breakpoint
CREATE TRIGGER "moment_comments_set_updated_at" BEFORE UPDATE ON "moment_comments"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- === Thread lookup ======================================================
-- Reading a post always asks "this post's published comments, oldest first" —
-- a thread reads forwards, unlike a feed. Index only the published rows so
-- hidden/deleted ones don't bloat it as moderation accumulates.

--> statement-breakpoint
CREATE INDEX "moment_comments_thread_idx"
  ON "moment_comments" ("moment_post_id", "created_at")
  WHERE "status" = 'published';

-- === Content rule =======================================================
-- Same reasoning as moment_posts_has_content_ck, and the same predicate that
-- 0022 had to correct: `btrim` trims spaces only, so test for the presence of a
-- non-whitespace character instead of trimming and comparing to ''.

--> statement-breakpoint
ALTER TABLE "moment_comments"
  ADD CONSTRAINT "moment_comments_has_body_ck"
  CHECK ("body" ~ '[^[:space:]]');

-- === Isolation: no PostgREST access to the new tables ===================
-- With RLS off, anon/authenticated must not reach these tables at all. The
-- public feed reads exclusively through the repository layer, which filters by
-- the event's public status and the row's published status — never by a
-- client-supplied tenant_id.

--> statement-breakpoint
REVOKE ALL ON TABLE public.moment_likes, public.moment_comments FROM anon, authenticated;
